# yaml-language-server: $schema=https://platen.io/schemas/config/schema.json
# Update to your own settings for URL/title
baseURL: https://fragrant-garden.netlify.app/
title:   Fragrant Garden

module:
  imports:
    - path: github.com/platenio/platen/modules/platen

menu:
  before:
    - name: Blog
      url: /posts
      weight: 10
  after:
    - name: Platen Documentation
      url: https://platen.io/
      weight: 10

params:
  description: charlotte's gallery
