# yaml-language-server: $schema=https://platen.io/schemas/config/schema.json
# Update to your own settings for URL/title
baseURL: https://fragrant.garden/
title:   Fragrant Garden

module:
  imports:
    - path: github.com/platenio/platen/modules/platen


params:
  description: charlotte's gallery

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    parser:
      attribute:
        block: true
        title: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: true